// TODO: Update `add_ticket`'s signature: it should take a `TicketDraft` as input
//  and return a `TicketId` as output.
//  Each ticket should have a unique id, generated by `TicketStore`.
//  Feel free to modify `TicketStore` fields, if needed.
//
// You also need to add a `get` method that takes as input a `TicketId`
// and returns an `Option<&Ticket>`.

use ticket_fields::{TicketDescription, TicketTitle};

#[derive(Clone)]
pub struct TicketStore {
    tickets: Vec<Ticket>,
    ticket_generator: IDGenerator,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct TicketId(u64);

#[derive(Clone, Debug, PartialEq)]
pub struct Ticket {
    pub id: TicketId,
    pub title: TicketTitle,
    pub description: TicketDescription,
    pub status: Status,
}

#[derive(Clone, Debug, PartialEq)]
pub struct TicketDraft {
    pub title: TicketTitle,
    pub description: TicketDescription,
}

#[derive(Clone, Debug, Copy, PartialEq)]
pub enum Status {
    ToDo,
    InProgress,
    Done,
}

impl TicketStore {
    pub fn new() -> Self {
        Self {
            tickets: Vec::new(),
            ticket_generator: IDGenerator::new(),
        }
    }

    pub fn add_ticket(&mut self, ticket: TicketDraft) -> TicketId {
        let new_id = self.ticket_generator.clone().ticket_id_gen();
        self.ticket_generator.next();
        let new_tick: Ticket = Ticket {
            id: new_id,
            title: ticket.title,
            description: ticket.description,
            status: Status::ToDo,
        };
        self.tickets.push(new_tick);
        new_id
    }

    pub fn get(&self, search_id: TicketId) -> Option<&Ticket>{
        for item in &self.tickets {
            if search_id == item.id {
                return Some(&item)
            } else {
                continue
            }
        }
    panic!("No ticket found")
    }
}


#[derive(Clone)]
pub struct IDGenerator {
    current_id: u64,
}

impl IDGenerator {
    fn new() -> Self {
        IDGenerator { current_id: 0 }
    }

    fn next(&mut self) -> () {
        self.current_id = self.current_id + 1;
    }

    fn ticket_id_gen(mut self) -> TicketId {
        self.next();
        TicketId (self.current_id.clone())
    }
}

#[cfg(test)]
mod tests {
    use crate::{Status, TicketDraft, TicketStore};
    use ticket_fields::test_helpers::{ticket_description, ticket_title};

    #[test]
    fn works() {
        let mut store = TicketStore::new();

        let draft1 = TicketDraft {
            title: ticket_title(),
            description: ticket_description(),
        };
        let id1 = store.add_ticket(draft1.clone());
        let ticket1 = store.get(id1).unwrap();
        assert_eq!(draft1.title, ticket1.title);
        assert_eq!(draft1.description, ticket1.description);
        assert_eq!(ticket1.status, Status::ToDo);

        let draft2 = TicketDraft {
            title: ticket_title(),
            description: ticket_description(),
        };
        let id2 = store.add_ticket(draft2);
        let ticket2 = store.get(id2).unwrap();

        assert_ne!(id1, id2);
    }
}
